Vagrant.configure("2") do |config|

	# Every Vagrant development environment requires a box. You can search for boxes at https://atlas.hashicorp.com/search.
	config.vm.box = "debian/jessie64"

	# Enable forwarding authentication requests from a remote host through an SSH tunnel to the original SSH client.
	config.ssh.forward_agent = true

	# Enable strict host-key verification to force SSH to check the remote host key against your `known_hosts` file, and if they don't match, to ask whether the key should be added to the `known_hosts` file.
	config.ssh.paranoid = true

	# Provision the system environment.
	config.vm.provision "shell" do |s|
		s.keep_color = true
		s.path = "https://gitlab.com/hyper-expanse/dotfiles/raw/master/.vagrant.d/system-provisioner.sh"
	end

	# Provision the user's environment.
	config.vm.provision "shell" do |s|
		s.keep_color = true
		s.path = "https://gitlab.com/hyper-expanse/dotfiles/raw/master/.vagrant.d/user-provisioner.sh"

		# The user provisioning script should run unprivileged, as the user itself.
		s.privileged = false
	end
end
