#!/usr/bin/env bash

# Capture our start time.
start=$(date +%s)

# Set the date for UTC date.
utcdate=$(date -u --rfc-3339=seconds)

# Location of the output log file.
log=/var/log/apt-updates

# Begin executing commands.
echo "*******************************************" >> $log
echo "[Apt Updates]: $utcdate Z" >> $log
echo "*******************************************" >> $log

# Update our list of repository packages
apt-get update >> $log

# Install all updated packages except for distribution updates. Assume yes where applicable (-y), show upgradable packages (-u), and do not install recommended packages but only those that are required (--no-install-recommends).
apt-get dist-upgrade -u -y --no-install-recommends -q >> $log

# Auto remove old packages and dependencies which are no longer needed.
apt-get autoremove -y >> $log

# Clean up cache files. Assume yes where applicable (-y).
apt-get clean -y >> $log

# Calculate and log total execution time.
end=$(date +%s)
difference=$(($end - $start))

echo >> $log
echo "Execution time: $difference seconds." >> $log
echo >> $log

