#!/usr/bin/env bash

# Capture our start time.
start=$(date +%s)

# Set the date for UTC date.
utcdate=$(date -u --rfc-3339=seconds)

# Location of the output log file.
log=/var/log/apt-updates

# Begin executing commands.
echo "*******************************************" >> $log
echo "[Aptitude Updates]: $utcdate Z" >> $log
echo "*******************************************" >> $log

# Update our list of repository packages
aptitude update >> $log

# Install all package updates where the update does not require the removal of another package. Assume yes where applicable (--assume-yes) and do not install recommended packages but only those that are required (--no-install-recommends).
aptitude safe-upgrade --assume-yes --without-recommends >> $log

# Clean up cache files. Assume yes where applicable (--assume-yes).
aptitude clean --assume-yes >> $log

# Calculate and log total execution time.
end=$(date +%s)
difference=$(($end - $start))

echo >> $log
echo "Execution time: $difference seconds." >> $log
echo >> $log

