jobs:
  shellcheck:
    container: ubuntu:20.04
    runs-on: ubuntu-latest
    container: koalaman/shellcheck-alpine:v0.7.0
    steps:
      - uses: actions/checkout@v2.3.4
      - run: sh test.sh
name: CI
on: [push, pull_request]
