jobs:
  shellcheck:
    runs-on: ubuntu-18.04
    container: koalaman/shellcheck-alpine:v0.7.0
    steps:
      - uses: actions/checkout@v2.3.4
      - run: sh test.sh
name: CI
on:
  push:
    branches:
      - '**'
