jobs:
  setup:
      runs-on: ubuntu-20.04
      steps:
        - name: checkout
          uses: actions/checkout@v2
          with:
            path: '.dotfiles'
        - name: setup
          run: sudo apt-get install build-essential curl file git
        - name: deploy
          run: bash deploy.sh
          working-directory: '.dotfiles'
        - name: setup
          run: ls -lA ~ && source ~/.profile && setupEnvironment
on:
  schedule:
    - cron: '2 2 * * *'
  push:
    branches:
      - test
