jobs:
  setup:
      runs-on: ubuntu-20.04
      steps:
        - name: checkout
          uses: actions/checkout@v2
          with:
            path: '.dotfiles'
        - name: setup
          run: sudo apt-get install build-essential curl file git
        - name: deploy
          run: bash deploy.sh
          working-directory: '.dotfiles'
        - name: setup
          run: |
            export HOMEBREW_DEBUG=true
            source ~/.profile
            source ~/.bashrc
            setupEnvironment
name: Homebrew
on:
  schedule:
    - cron: '2 2 * * *'
  push:
    branches:
      - '**'
    path:
      - '.bash_functions'
  pull_request:
    branches:
      - '**'
    path:
      - '.bash_functions'
