defaults:
  run:
    working-directory: .dotfiles
jobs:
  setup:
      runs-on: ubuntu-20.04
      steps:
        - name: setup
          run: apt-get install build-essential curl file git
        - name: deploy
          run: bash deploy.sh
        - name: setup
          run: source ~/.profile && setupEnvironment
on:
  schedule:
    - cron: '2 2 * * *'
  push:
    branches:
      - test
