jobs:
  setup:
    container: ubuntu:20.04
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          path: '.dotfiles'
      - name: setup
        run: sudo apt-get install build-essential curl file git
      - name: deploy
        run: bash deploy.sh
        working-directory: '.dotfiles'
      - name: setup
        run: |
          source ~/.profile
          source ~/.bashrc
          setupEnvironment
name: Homebrew
on:
  schedule:
    - cron: '2 2 * * *'
  push:
    branches:
      - '**'
    path:
      - '.bash_functions'
  pull_request:
    branches:
      - '**'
    path:
      - '.bash_functions'
